FROM python:3.12-slim

WORKDIR /app

# Копируем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код
COPY . .

# Устанавливаем рабочую директорию для сайта
WORKDIR /app/orders_site

# Запускаем сайт
CMD ["python", "app.py"]

