from aiogram import Router, F, types
from aiogram.fsm.context import FSMContext
from aiogram.fsm.state import StatesGroup, State

class LocationAdminStates(StatesGroup):
    deleting = State()
    editing_name = State()
    editing_address = State()

def register_admin_locations(router: Router, db):
    @router.message(F.text == "🌍 Список локаций")
    async def admin_list_locations(...): ...
    @router.message(F.text == "🌍 Управление локациями")
    async def manage_locations(...): ...
    @router.callback_query(F.data.startswith("admin_loc_add"))
    async def add_location_start(...): ...
    @router.message(StateFilter(LocationAdminStates.editing_name))
    async def process_new_location_name(...): ...
    @router.message(StateFilter(LocationAdminStates.editing_address))
    async def process_new_location_address(...): ...
    @router.callback_query(F.data.startswith("admin_loc_delete:"))
    async def confirm_delete_location(...): ...
    @router.callback_query(StateFilter(LocationAdminStates.deleting), F.data == "admin_loc_confirm_delete")
    async def delete_location_confirm(...): ...
    @router.callback_query(StateFilter(LocationAdminStates.deleting), F.data == "admin_loc_cancel_delete")
    async def cancel_delete_location(...): ...
    @router.callback_query(F.data.startswith("admin_loc_edit:"))
    async def edit_location_stub(...): ...
